FrontendSimf20016/team2

common.blocks/body/body.bemtree.js, common.blocks/footer/footer.bemtree.js, common.blocks/header/header.bemtree.js, common.blocks/input/input.css, common.blocks/layout/layout.css, common.blocks/page/page.deps.js, common.blocks/search-icon/search-icon.bemhtml.js, common.blocks/search-icon/search-icon.css, common.blocks/search-icon/search-icon.svg
Search Style (style is bad for iPhone 4 but will adjust later)
=> Search Style

.gitignore, package.json, server/index.js
для переменных я использовал .env файл. 
еще ENV переменные можно установить в системе или при запуске ноды, но пока из файла. Если эти переменные не установить может вылезти ошибка. Так же npm i после обновления репозитория
вот содержимое файла .env который нужно будет создать к корне
CLIENT_ID=640286839471900
CLIENT_SECRET=22638314f50401085d755dc9d5430d50
VKONTAKTE_APP_ID=3202360
VKONTAKTE_APP_SECRET=LJM4H45GbaTkzItX2St3
=> Авторизация в ФБ и VK

common.blocks/header-menu/header-menu.bemtree.js
Adding correct lick to Slava Page (Edit Profile)
=> Adjustment link to Edit Profile

common.blocks/_type/input_type_file.bemhtml.js, common.blocks/input/_type/input_type_file.bemhtml.js, common.blocks/label/label.bemhtml.js, common.blocks/settings-list/settings-list.bemtree.js, common.blocks/settings-list/settings-list.css, common.blocks/settings-list/settings-list.deps.js
Сделал модификатор для input: type=file. 
Вынес label в отдельный блок.
=> Оптимизировал bemtree в settings-list.

common.blocks/avatar/avatar.bemtree.js, common.blocks/avatar/avatar.css, common.blocks/profile/profile.bemtree.js, common.blocks/seed-list/seed-list.bemtree.js
Блок avatar модифицирован для использования в любом месте проекта
=> Avatar Block usage

common.blocks/attach/__control/attach__control.bemhtml.js, common.blocks/input/__control/input__control.bemhtml.js, common.blocks/input/input.bemhtml.js, common.blocks/settings-list/settings-list.bemtree.js, server/createDB.js, server/index.js
В скрипте createDB указал id для тестовых юзеров, чтобы у всех они были одинаковые.
=> выполнить `node server/createDB.js`
Временные зоны теперь сохраняются в базу и тянутся из базы.
=> Оптимизация кода. Временные зоны. id у тестовых юзеров

.eslintrc, package.json
преимущество в том, что есть поддержка BEM файлов
никаких хуков нет, можно будет закомититься и с ошибками, так что смотрим сами у себя в редакторах какие ошибки
=> Добавлен конфиг для линтера.

.gitignore, server/ctl/userCtrl.js, server/routes.js
Вернул то, что пропало. 
Сделал сохранение аватара файлом именованым ником пользователя. - исключает замещение чужих аватарок.
=> Поправил + Аватар сохраняется по нику юзера

common.blocks/profile/profile.bemtree.js, server/ctl/seedCtrl.js, server/models/seed.js, server/routes.js
Вынес метод выборки сидов _(пока правда без фильтра, что это должны быть сиды юзеров на кого он подписан)_ в модель Сида - в метод plainSeed - он возвращает сиды сразу с данными авторов.
=> Оптимизация метода выборки сидов и передача количества сидов у юзера

common.blocks/followed-unfollowed/followed-unfollowed.bemtree.js, common.blocks/followed-unfollowed/followed-unfollowed.css, common.blocks/followed-unfollowed/followed-unfollowed.js, common.blocks/page/page.deps.js, common.blocks/seed-list-item/seed-list-item.bemtree.js, common.blocks/seed-list-item/seed-list-item.deps.js, common.blocks/seed-list/seed-list.bemtree.js, server/models/seed.js
Это блок - подписаться отписаться
=> Верстка для блока подписки

common.blocks/content/content.css, common.blocks/page/_view/page_view_viewProfile.bemtree.js, common.blocks/page/page.deps.js, common.blocks/view-profile/view-profile.bemhtml.js, common.blocks/view-profile/view-profile.bemtree.js, common.blocks/view-profile/view-profile.css, common.blocks/view-profile/view-profile.deps.js, server/ctl/userCtrl.js, server/render.js, server/routes.js
Роут на страницы пользователей.
Отображение сидов пользователя
Отображение информации пользователя.
=> Страницы пользователей

common.blocks/addSeed/addSeed.bemhtml.js, common.blocks/addSeed/addSeed.css, common.blocks/addSeed/addSeed.deps.js, server/ctl/seedCtrl.js, server/routes.js
=> Сохранение сида от текущего юзера

common.blocks/content/content.css, common.blocks/input/input.css, common.blocks/page/_view/page_view_viewProfile.bemtree.js, common.blocks/view-profile/view-profile.bemhtml.js, common.blocks/view-profile/view-profile.bemtree.js, common.blocks/view-profile/view-profile.js, server/ctl/userCtrl.js, server/models/user.js, server/routes.js
Поправил роут.
Реализована подписка/отписка на странице пользователя.
Кнопка подписки меняется в зависимости от состояния подписки и признака своего профиля.
Чуть поправил стиль уведомления для input.
=> Подписка/отписка. Пересчет подписавшихся. Динамическая кнопка подписки.

.enb/make.js, .gitignore, common.blocks/followed-unfollowed/followed-unfollowed.bemhtml.js, common.blocks/page/_view/page_view_home.bemtree.js, common.blocks/root/root.bemtree.js, common.blocks/seed-list-item/seed-list-item.bemhtml.js, common.blocks/seed-list/seed-list.bemtree.js, common.blocks/seed-list/seed-list.js, server/ctl/seedCtrl.js, server/models/seed.js, server/routes.js
При скролле до конца страницы подгружаются старые сиды. Установлен лимит в 6 сидов за раз. Можно будет вынести в конфиг.
Из особенностей обратите внимание, что некоторые .bemtree были переведены в .bemhtml и проброшены на клиентскую сторону.
=> Подгрузка старых сидов

common.blocks/page/_view/page_view_view.bemtree.js, common.blocks/page/page.deps.js, server/ctl/seedCtrl.js, server/ctl/userCtrl.js, server/routes.js
Я запушила рул реквкст, чтобы проще было мерджить в местах общего пользования. Весь дальнейший код никому уже не помешает
=> Структура для страницы Seed View Page

server/models/seed.js
Список тегов понадобится при поиске.
=> Индексирование хэштегов при сохраненни сида

common.blocks/addSeed/addSeed.css, common.blocks/avatar/avatar.css, common.blocks/content/content.css, common.blocks/followed-unfollowed/followed-unfollowed.css, common.blocks/header-menu/header-menu.bemtree.js, common.blocks/input/input.css, common.blocks/layout/layout.css, common.blocks/link/_theme/link_theme_greylink.css, common.blocks/page/_view/page_view_home.bemtree.js, common.blocks/profile/profile.bemhtml.js, common.blocks/profile/profile.css, common.blocks/profile/profile.js, common.blocks/search-icon/search-icon.css, common.blocks/seed-list-item/seed-list-item.css, common.blocks/settings-list/settings-list.bemtree.js, common.blocks/settings-list/settings-list.css, common.blocks/settings-setup-list/settings-setup-list.css, common.blocks/subscribe-button/subscribe-button.bemhtml.js, common.blocks/subscribe-button/subscribe-button.js, server/ctl/seedCtrl.js, server/ctl/userCtrl.js, server/models/user.js, server/routes.js
Навёл порядок в i-bem
Добавил проверку авторизации где не было.
Поправил пункты меню.
Ну и заодно причесал стили.
=> Рефакторинг

README.md, common.blocks/page/_view/page_view_viewSubscription.bemtree.js, common.blocks/page/page.deps.js, common.blocks/profile/profile.bemhtml.js, common.blocks/subscribe-button/subscribe-button.bemhtml.js, common.blocks/subscribe-button/subscribe-button.js, server/ctl/userCtrl.js, server/models/user.js, server/routes.js
Страница, на которой отображаются подписки пользователя или подписавшиеся. С внешним видом не стал заморачиваться, думаю не критично.
Теперь есть роут GET `/profile/:nick/:action` для различных действий с профилем:
- подписаться/отписаться `action = subscribe` + `params = {userId: userId}`
- показать подписчиков `action = subscribers`
- показать подписки `action = follow`
=> Страница подписки и подписчики

common.blocks/page/_view/page_view_home.bemtree.js, common.blocks/seed-list/seed-list.bemtree.js, server/ctl/userCtrl.js, server/models/seed.js, server/routes.js
На главной странице только те сиды, на чьих авторов мы подписаны
На странице профиля - только сиды профиля
=> Отображение целевых сидов

common.blocks/page/_view/page_view_home.bemtree.js, common.blocks/page/_view/page_view_viewProfile.bemtree.js, common.blocks/seed-list-item/seed-list-item.bemhtml.js, common.blocks/seed-list-item/seed-list-item.css, common.blocks/seed-list-item/seed-list-item.deps.js, server/models/seed.js
#69 - `../../` теперь нету
Убрал блок профиль с главной страницы. 
Сделал блок профиль в seed-list-item. 
Чуть изменил внешний вид сида. 
Выдачу списка сидов сделал не плоской, ибо нужен блок профиля. 
Количество выдачи сидов увеличил до 10 ибо не всегда появлялся скролл = не загружались старые сиды.
=> Порефакторил seed-list-item

common.blocks/header-notification/header-notification.bemhtml.js, common.blocks/header-notification/header-notification.css, common.blocks/header-notification/header-notification.deps.js, common.blocks/header-notification/header-notification.js, common.blocks/header/header.bemtree.js, common.blocks/header/header.css, common.blocks/page/_view/page_view_home.bemtree.js, common.blocks/page/page.css, common.blocks/page/page.deps.js, common.blocks/seed-list/seed-list.deps.js, common.blocks/seed-list/seed-list.js, server/ctl/seedCtrl.js, server/models/seed.js, server/routes.js
Информирование о новых сидах
Получение новых сидов
подозреваю, что работает оно только на главной ленте. починю на все ленты в следующем пр
=> Seed notification

common.blocks/input/input.css, common.blocks/seed-list-item/seed-list-item.bemhtml.js, server/ctl/seedCtrl.js, server/routes.js
Cсылку вида /seed/view/?id = 57c5a7b7834f4e2c7b5a6cd0/  поменяла на ссылку вида /seed/view/57c5a7b7834f4e2c7b5a6cd0/
=> Изменение вида ссылки на ответы

common.blocks/page/_view/page_view_viewProfiles.bemtree.js, common.blocks/page/page.deps.js, server/ctl/userCtrl.js, server/models/user.js, server/routes.js
по url отображается лист профайлов (пока без лимита)
Большая просьба Сережа и Слава (мне кажется к вам это ближе) посмотрите пожалуйста, почему мне в строку 108 файла userCrtl.js  не приходит req.user._id (точнее user вообще).
=> Profiles Page

common.blocks/login/login.bemtree.js
ссори за такой diff (что все красное)
на самом деле просто автоматически выровнял отступы и
добавил
```js
{
elem: 'center',
content: {
block: 'link',
url: '/',
content:{
block: 'image',
url: '/img/pepo.png'
}
}
},
```
=> Логотип на страницу логина

common.blocks/avatar/avatar.css, common.blocks/content/content.css, common.blocks/profile/profile.bemhtml.js, common.blocks/profile/profile.css, common.blocks/seed-list-item/seed-list-item.bemhtml.js, common.blocks/seed-list-item/seed-list-item.css, common.blocks/subscribe-button/subscribe-button.bemhtml.js, common.blocks/subscribe-button/subscribe-button.js
#77 Нормальный перенос текста вокруг аватара
Аватар - ссылка.
В сидах кнопки ответить не прыгают из-за признака "Это ответ"
=> Блок профиль.

server/index.js
Регулярку не торгал, заменил ник по-умолчанию
=> горячий фикс ника по-умолчанию

common.blocks/page/_view/page_view_home.bemtree.js, common.blocks/page/page.deps.js, common.blocks/settings-setup-list/settings-setup-list.bemtree.js
Поправил profile/setup.
Написал вступительное слово для новых пользователей.
=> Написал Hello World =)

common.blocks/seed-list-item/seed-list-item.bemhtml.js, package.json
почему-то не собиралось без добавки в package.json
=> вывод в сид-айтем fromData и добавление момента а .json файлы
